### ISSUE TITLE
[BUG] warning still shown

### ISSUE THREAD

**Issue by kedorlaomer** [christopherpickering/pylint-per-file-ignores#54]
## System Info

- Browser: N/A
- OS: Windows 10
- version of pylint: 2.17.4

## Issue

After configuring via `pyproject.toml` that certain warnings in a certain sub-subdirectory should be ignored, they are still being shown.

## How To Reproduce

* Add a block `load-plugins = ["pylint_per_file_ignores"]`
* Add a block
 
        [tool.pylint-per-file-ignores]
        "/cool_project/db_models/"="C0301,line-too-long"
* Run `python -pylint cool_project` in `cool_project`'s root directory
* Observe warnings about long lines in `/cool_project/db_models/model1.py`

Notes:
1. The line about `db_models` is being processed. I verified this by adding `print` statements to `pylint-per-file-ignores`'  `__init__.py`.
2. Leading and trailing `/` in the file name are not relevant.
3. Likewise, the windows-native spelling with `\\\\` (need four backslashes for proper escaping) does not help.

**Comment by christopherpickering** [comment]
Thanks for reporting, I've updated the matching logic to fix this. Not sure if something changed on the pylint side or if this has been busted for a while... there are no tests to prove either :) Let me know if you run into other problems. On the side, I'd recommend you check out ruff.
